language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
sudo: false
env:
    - MP_FAKEMONGO=true
cache:
    - pip
    - apt
addons:
  apt:
    packages:
    - python-scipy
    - libblas-dev
    - liblapack-dev
    - gfortran
    - python-pip
install:
  - "easy_install -U setuptools"
  - "pip install -r requirements.txt"
  - "pip install -r requirements-ci.txt"
# This is needed, otherwise, nosetests can't find the installed pymatgen C
# extensions.
before_script:
  - python setup.py develop
# command to run tests, e.g. python setup.py test
script: nosetests
notifications:
  email:
    recipients:
#      - shyuep@gmail.com
      - dkgunter@lbl.gov
    on_success: change
    on_failure: always
