branches:
  except:
    - gh-pages

environment:
  matrix:
    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      platform: x64
      STANDALONE: "FALSE"
      CONDA_PY: "35"
      CONDA_BUILD: "TRUE"
      SPLIT_RUN: "FALSE"
  MAPI_KEY:
    secure: XIbk1W27nucVUHTVpIL2B+FodL9w2Efyw5PqTdnfbHg=
  PYPIPWD:
    secure: QPpXonUAeLJ8p3f936jh7g==

services:
  - mongodb

install:
  # Add the paths
  - 'set PATH=%PYTHON%;%PYTHON%\Library\bin;%PYTHON%\Scripts;%PATH%'
  # Check that we have the expected version and architecture for Python
  - 'python --version'
  - 'python -c "import struct; print(struct.calcsize(''P'') * 8)"'

  # Install the build dependencies of the project via conda and pip
  - 'conda install --yes --quiet numpy scipy matplotlib setuptools wheel'
  - 'conda install --yes --quiet --channel matsci spglib'
  - "pip install -r requirements.txt"
  - "pip install -r requirements-ci.txt"

  # Run develop to install in dev mode and build C extension.
  - "python setup.py develop"

build: false

test_script:
  - IF NOT "%APPVEYOR_REPO_BRANCH%" == "stable" (nosetests)

notifications:
  - provider: Email
    to:
      - shyuep@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

deploy_script:
   - "pip install twine"
   - IF "%APPVEYOR_REPO_BRANCH%" == "stable" (python setup.py sdist bdist_wheel)
   - IF "%APPVEYOR_REPO_BRANCH%" == "stable" (twine upload --username Shyue.Ping.Ong --password %PYPIPWD% dist/*.whl)
